### ISSUE TITLE
feat: Base implementation for Grid

### ISSUE THREAD

**Issue by Bugaa92** [stardust-ui/react#11]
## Feature Request
OP: @levithomason linked from [react-old/issues/97](https://github.com/stardust-ui/react-old/issues/97)

# Grid

This API proposal is for creating a minimal _base_ implementation of a Grid component.  I propose this is done using CSS Grid syntax, respecting IE 11 shortcomings (no gap, no template areas).

Helpful resource: https://learncssgrid.com

### columns (quantity)

A Grid can define an arbitrary number of columns of equal width.

```jsx
<Grid columns='3'>  //=> { display: grid; grid-template-columns: 1fr 1fr 1fr; }
  <Box>1</Box>
  <Box>2</Box>
  <Box>3</Box>
</Grid>
```
>A `string` or a `number` should be accepted.

![image](https://user-images.githubusercontent.com/5067638/42800788-0f0367d4-8952-11e8-87e7-a23c00defbdb.png)

### columns (explicit)

A Grid can explicitly define columns and their sizes.

For now, this is simply using the `grid-template-columns` value syntax.  Proposing we consider more useful abstractions later.

```jsx
<Grid columns='90px 50px 120px'> //=> { display: grid; grid-template-columns: 90px 50px 120px; }
  <Box>1</Box>
  <Box>2</Box>
  <Box>3</Box>
  <Box>4</Box>
  <Box>5</Box>
  <Box>6</Box>
</Grid>
```

![image](https://user-images.githubusercontent.com/5067638/42800597-707a686a-8951-11e8-9053-10fe75a6bae6.png)

### rows (quantity)

**Note**, unlike the columns I'm not proposing a way of defining an arbitrary number of rows.  Rows are created automatically when columns wrap.  Therefore, it makes no sense to say a Grid will have X rows ahead of time.

It may prove useful to be able to say "assign this value to all rows", however, I'm leaving this out of the base implementation proposal.

### rows (explicit)

A Grid can explicitly define the sizes of its rows.

For now, this is simply using the `grid-template-rows` value syntax.  Proposing we consider more useful abstractions later.

```jsx
<Grid rows='50px 100px'> //=> { display: grid; grid-template-rows: 50px 100px; }
  <Box>1</Box>
  <Box>2</Box>
  <Box>3</Box>
  <Box>4</Box>
  <Box>5</Box>
  <Box>6</Box>
</Grid>
```

**Comment by levithomason** [comment]
>###rows (quantity)

Looking back, this is short sighted.  If you have a grid with a fixed height, you very well may want to equally divide up that vertical space by passing a number of rows.  Let's give the same API to rows as columns has.

**Comment by levithomason** [comment]
We need to ensure the grid renders correctly with the requirements here: https://github.com/stardust-ui/react/issues/29
