### ISSUE TITLE
[RFC] Alternatives to Awkward Variant Modifiers

### ISSUE THREAD

**Issue by davezuko** [stardust-ui/react#2]
Linked from https://github.com/stardust-ui/react-old/issues/2.

### Problem description

In Semantic UI V1 we supported modifiers/variants such as:

```js
<Button basic />        // this is cool
<Button basic="very" /> // this is not
```

The problem with this is that it's extremely unintuitive, reads awkwardly, and overloads what should be a boolean or otherwise mutually exclusive property (`basic`).

### Proposed solution

This issue is designed to encourage conversation around alternatives to this problem. One simple idea would be to support something like:

```js
<Button basic />
<Button veryBasic />
```

Better ideas are encouraged.

**Comment by levithomason** [comment]
We are dealing with this on a case by case basis.  The agreement is to not have any property-value pairs that make for awkward english reading.
