### ISSUE TITLE
CSS in JS issues

### ISSUE THREAD

**Issue by levithomason** [stardust-ui/react#66]
We'll track CSS in JS issues we're having here and propose solutions later.

1. Cannot switch to a different renderer (normal, rtl) during the life of the app #58 
2. We'll need to support multiple React roots on a single page.

**Comment by robinweser** [comment]
@levithomason FWIW, we're thinking about introducing dynamic direction support, adding the ability to switch rtl => ltr dynamically as well as having different modes for different sub trees :) 

PS: I was thrilled to see Fela in the code here. Looks like a very promising UI library. If there's anything I can help with, feel free to hit me up =)

**Comment by levithomason** [comment]
>we're thinking about introducing dynamic direction support

That would be awesome.  This is one of the big hurdles for us now.

The other goal we have is to reduce the number of wrapping components around every UI component.  This is the reason we are using the renderer directly opposed to an HOC.

**Comment by miroslavstastny** [comment]
3. Fela does not prefix keyframe class names - RTL keyframes rewrite LTR ones #516

**Comment by miroslavstastny** [comment]
4. Fela incompatible with `--isolatedModules` #613

**Comment by layershifter** [comment]
After #1459 we will not need to switch renderers.
Fela is also compatible with TS `--isolatedModules` now 🚀

**Comment by levithomason** [comment]
Both the original issues are now solved 💪
