### ISSUE TITLE
List item header does not have rem size

### ISSUE THREAD

**Issue by tomasiser** [stardust-ui/react#71]
### Steps
- Open the List example at https://stardust-ui.github.io/react/components/list,
- open DevTools in Chrome (or another browser),
- manually change the `font-size` of `body` from `1rem` to another value, e.g. `2rem` or `50px`.

![image](https://user-images.githubusercontent.com/10374559/43890866-2da82f70-9bc8-11e8-8262-db4786b673e6.png)

### Expected Result
Nothing should change with the List, it still should look the same:
![image](https://user-images.githubusercontent.com/10374559/43890944-68f9b206-9bc8-11e8-97df-cd12200719b7.png)

### Actual Result
The header of the list scales with the `body` `font-size`, but the rest of the list does not. That happens because the header uses the `body` styling and not its own `rem` based styling. Stardust should probably not enforce its consumers to specify `1rem` in their `body` `font-size`.
![image](https://user-images.githubusercontent.com/10374559/43891018-9797cab2-9bc8-11e8-9d66-53c8fe451476.png)

### Version
0.2.6

**Comment by mnajdova** [comment]
Thanks for catching this, will be address in my PR: https://github.com/stardust-ui/react/pull/60
